apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-database
  namespace: auth
  labels:
    app: auth-database
spec:
  serviceName: auth-database
  replicas: 1
  selector:
    matchLabels:
      app: auth-database
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      containers:
      - name: auth-database
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
          name: db-port
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      dnsPolicy: ClusterFirst
      volumes:
      - name: mysql-initdb
        configMap:
          name: auth-database-config
          items: 
          - key: initdb.sql
            path: initdb.sql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-database
  namespace: auth
  labels:
    app: auth-database
spec:
  ports:
  - port: 3306
    name: db-port
  selector:
    app: auth-database