name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Maven project
      run: mvn package -DskipTests
    - name: Copy files
      run: |
        cd auth-service/target
        find -name "*-sources.jar" -exec rm {} \;
        find -name "*-javadoc.jar" -exec rm {} \;
        jarName=`find *.jar`
        tagName=${jarName%.jar}
        tagName=${tagName#auth-service-}
        cp $jarName ../../auth-service.jar
        echo "jarName=$jarName" >> $GITHUB_ENV
        echo "tagName=$tagName" >> $GITHUB_ENV
    - name: Build and push Service Docker images
      uses: docker/build-push-action@v2.3.0
      with:
        context: .
        push: true
        tags: dustlightcn/auth-service:${{  env.tagName  }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - name: Build the Vue project
      run: |
        cd auth-ui
        npm i
        npm install @quasar/cli
        quasar build
    - name: Build and push UI Docker images
      uses: docker/build-push-action@v2.3.0
      with:
        context: auth-ui
        push: true
        tags: dustlightcn/auth-ui:${{  env.tagName  }}
    - name: Quasar Build
      run: |
        cd auth-ui
        quasar build
    
