name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Maven project
      run: mvn package -DskipTests
    - name: Copy files
      run: |
        cd auth-service/target
        find -name "*-sources.jar" -exec rm {} \;
        find -name "*-javadoc.jar" -exec rm {} \;
        jarName=`find *.jar`
        tagName=${jarName%.jar}
        tagName=${tagName#auth-service-}
        cp $jarName ../../auth-service.jar
        cd ../../
        echo "jarName=$jarName" >> $GITHUB_ENV
        echo "tagName=$tagName" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.3.0
      with:
        push: true
        tags: dustlightcn/auth-service:${{  env.tagName  }}
